[package]
name = "gaussian_sk"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
pariter = "0.5.1"
plotters = "0.3"
rand = "0.8"
rand_distr = "0.4"
rayon = "1.5"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
